Add provisioning of LXC containers for nextcloud. (#5)
- Install geerlingguy.apache role.
- Configure user accounts on proxmox nodes.
- Fix install-dependencies so it can run without an inventory during
bootstrap.
- Add bootstrap scripts to proxmox nodes.
- Cleanup ansible-pull bootstrap scripts.
- Add role for creating proxmox LXC containers.
- Add playbook and configuration for local PVE containers.
- Add mount configuration options to lxc definition.
- Configure nextcloud hosts.
- Add support for bindmounts to lxc configuration.
- Allow bootstrapping to occur from a branch.
- Start nextcloud VMs.
- Improve playbook error handling.
- Disable setting owner for backup folders, to temporarily fix bindmount
issues.
- Configure nextcloud backup bindmounts.

diff --git a/roles/ansible-pull/templates/usr/local/bin/run-playbooks b/roles/ansible-pull/templates/usr/local/bin/run-playbooks
--- a/roles/ansible-pull/templates/usr/local/bin/run-playbooks
+++ b/roles/ansible-pull/templates/usr/local/bin/run-playbooks
@@ -10,12 +10,19 @@ else
   gitRef=main
 fi
 
-set -x
+set +e
 
 /usr/bin/ansible-pull \
   --checkout "${gitRef}" \
   --inventory inventory \
+  --purge \
   --sleep "${sleepTime}" \
   --url https://github.com/skleinjung/ansible.git \
   --vault-password-file "{{ ansible_secret_path }}" \
-  "$@"
+  "$@" >>/var/log/ansible.log 2>&1
+
+result="$?"
+if [ $result != "0" ]; then
+  echo "Playbook failed! See /var/log/ansible.log for details."
+  exit 1
+fi
